var:
  url-repo: https://github.com/ludo2ne/ENSAI-2A-Big-Data   # to call this value : {{< meta var.url-repo >}}

project:
  type: website
  render:
    - "**/*.qmd"

website:
  title: "Big Data"
  repo-url: "{{< meta var.url-repo >}}"
  repo-branch: main
  reader-mode: true
  navbar:
    background: "#447099"
    left:
      - href: index.qmd
        text: Home
      - text: Labs
        menu:
          - href: docs/lab/lab-setup.qmd
            text: "Lab setup"
          - href: docs/lab/lab0/lab0.qmd
            text: "Lab 0"
          - href: docs/lab/lab1/lab1.qmd
            text: "Lab 1"
          - href: docs/lab/lab2/lab2.qmd
            text: "Lab 2"
          - href: docs/lab/lab3/lab3.qmd
            text: "Lab 3"
      - text: AWS
        menu:
          - href: docs/lab/aws-cluster-spark.qmd
            text: "Create a Spark cluster"
          - href: docs/lab/aws-stream-simulation.qmd
            text: "Stream Simulation AWS"
          - href: docs/lab/ssp-stream-simulation.qmd
            text: "Stream Simulation SSP"
    right:
      - text: Other resources
        menu:
          - href: docs/sspcloud.qmd
            text: "SSPCloud"
          - href: docs/duckdb.qmd
            text: "DuckDB"
      - href: docs/resources.qmd
        text: Useful resources
      - icon: github
        href: "{{< meta var.url-repo >}}"
        target: "_blank"
  reader-mode: true
  page-footer:
    right: |
      Website built with [Quarto](https://quarto.org/){.external target="_blank"} <br>
      [Source code]({{< meta var.url-repo >}}){.external target="_blank"}

format:
  html:
    theme:
      dark: solar
      light: cosmo
    css: styles.css
