
project:
  type: website
  render:
    - "**/*.qmd"

website:
  title: "Big Data"
  navbar:
    background: "#447099"
    left:
      - href: index.qmd
        text: Home
      - text: Labs
        menu:
          - href: docs/lab/lab-setup.qmd
            text: "Lab setup"
          - href: docs/lab/lab0/lab0.qmd
            text: "Lab 0"
          - href: docs/lab/lab1/lab1.qmd
            text: "Lab 1"
          - href: docs/lab/lab2/lab2.qmd
            text: "Lab 2"
          - href: docs/lab/lab3/lab3-SSPCloud.qmd
            text: "Lab 3"
      - text: AWS
        menu:
          - href: docs/lab/aws-cluster-spark.qmd
            text: "Create a Spark cluster"
            
      - text: Other resources
        menu:
          - href: docs/duckdb.qmd
            text: "DuckDB"
      - href: docs/bibliography.qmd
        text: Bibliography
    right:
      - icon: github
        href: https://github.com/ludo2ne/ENSAI-2A-Big-Data
        target: "_blank"
  reader-mode: true
  page-footer:
    right: |
      Website built with [Quarto](https://quarto.org/){.external target="_blank"} <br>
      [Source code](https://github.com/ludo2ne/ENSAI-2A-Big-Data){.external target="_blank"}

format:
  html:
    theme:
      dark: solar
      light: cosmo
    css: styles.css
