
project:
  type: website
  render:
    - "**/*.qmd"
    - "**/*.ipynb"

website:
  title: "Big Data"
  navbar:
    background: "#447099"
    left:
      - href: index.qmd
        text: Home
      - text: Labs
        menu: 
          - href: docs/lab/lab-setup.qmd
            text: "Lab setup"
          - href: docs/lab/lab0/lab0.qmd
            text: "Lab 0"
          - href: docs/lab/lab1/lab1-SSPCloud.ipynb
            text: "Lab 1"
          - href: docs/lab/lab2/lab2-SSPCloud.ipynb
            text: "Lab 2"
          - href: docs/lab/lab3/lab3.qmd
            text: "Lab 3"
    right:
      - icon: github
        href: https://github.com/ludo2ne/ENSAI-2A-Big-Data
        target: "_blank"        
  page-footer:
    right: |
      Website built with <a href=https://quarto.org/ target="_blank">Quarto</a><br>
      <a href=https://github.com/ludo2ne/ENSAI-2A-Big-Data target="_blank">Source code</a>
  repo-url: https://github.com/ludo2ne/ENSAI-2A-Big-Data
  repo-branch: main
  issue-url: https://github.com/ludo2ne/ENSAI-2A-Big-Data/issues/new
  repo-actions: [edit, issue]

format:
  html:
    theme: 
      dark: solar
      light: cosmo



