---
title: "Introduction to Big Data"
format: html
from: markdown+emoji
---


# :construction: 

Lessons and Labs created by [Rémi Pépin](https://github.com/HealerMikado/panorama_big_data_2021){target="_blank"} and [Arthur Katossky](https://github.com/katossky/panorama-bigdata){target="_blank"}

# :dart: Objectives

- Understand the basics of computation in the real world, the bottlenecks and how to solve them
- Understand the basics of cloud computing and how to use AWS (or SSP Cloud)
- Get familiar with big data technologies and the most common paradigm
- Learn how to use Spark for data exploration on data at rest or streamed data, and how to use some basics ML algorithm on big data


# :calendar: Organisation 

- Lessons : 7h30
- Labs : 10h30 + 3h (graded lab)
- Presentations : 3h

# :arrow_forward: Lessons


## :arrow_forward: Objectives

* Understand the basics of computation in the real world
* Understand the basics of cloud computing and how to use AWS
* Get familiar with big data technologies
* Learn how to use Spark for data exploration

---

## :arrow_forward: Lessons
 
### :small_blue_diamond: 1.1 What is Big Data

* What is considered big ?
* Volume, Velocity, Variety, Veracity, Value, Variability

### :small_blue_diamond: 1.2 Computer science survival kit

* Processors, Memory, Storage, Network

### :small_blue_diamond: 1.3 High-performance computing without distribution

* Profile code, Analyse code
* Store or process data in chunks, Take advantage of sparcity
* Go low-level
* Use cache

### :small_blue_diamond: 1.4 What if ?

* What if data is too big to fit in memory ?
* What if your file is too big for your local file system ?
* What if data is too big to fit on disk ?
* What if computation takes ages ?
* What if computation / storage is too expensive ?

### :small_blue_diamond: 1.5 Social issues

* Ethical issues, Environmental issues, Political issues

---

### :small_blue_diamond: 2.1 How to store big data

* File system, Database, Distribution 
* The CAP theorem

### :small_blue_diamond: 2.2 Hadoop file system (HDFS)

* Hadoop Ecosystem, How to use HDFS


### :small_blue_diamond: 2.3 Hadoop MapReduce

* Key Concepts

### :small_blue_diamond: 2.4 Spark

* Key Concepts
* Importing/Exporting data
* How to run Spark ?

---

### :small_blue_diamond: 3 Cloud Computing

* Traditional IT, Virtualization, Containerization
* Why cloud computing ?
* categories of cloud services


# :arrow_forward: Labs

* [Lab 0](docs/lab/lab0/lab0.qmd) : Discover Amazon Web Service (AWS)
* [Lab 1](docs/lab/lab1/lab1.qmd) : First steps with Spark
* Lab 2
* [Lab 3](docs/lab/lab3/lab3.qmd) : Stream processing with Spark